/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SpeedFrameModule"
 * 	found in "./SpeedFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_AdvisorySpeed_H_
#define	_AdvisorySpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AdvisorySpeedType.h"
#include "SpeedAdvice.h"
#include "SpeedConfidence.h"
#include "ZoneLength.h"
#include "RestrictionClassID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AdvisorySpeed */
typedef struct AdvisorySpeed {
	AdvisorySpeedType_t	 type;
	SpeedAdvice_t	*speed	/* OPTIONAL */;
	SpeedConfidence_t	*confidence	/* OPTIONAL */;
	ZoneLength_t	*distance	/* OPTIONAL */;
	RestrictionClassID_t	*Class	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisorySpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisorySpeed;
extern asn_SEQUENCE_specifics_t asn_SPC_AdvisorySpeed_specs_1;
extern asn_TYPE_member_t asn_MBR_AdvisorySpeed_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisorySpeed_H_ */
#include <asn_internal.h>
