/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DataElementsModule"
 * 	found in "./DataElementsModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CostToParkType_H_
#define	_CostToParkType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CostToParkType */
typedef long	 CostToParkType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CostToParkType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CostToParkType;
asn_struct_free_f CostToParkType_free;
asn_struct_print_f CostToParkType_print;
asn_constr_check_f CostToParkType_constraint;
ber_type_decoder_f CostToParkType_decode_ber;
der_type_encoder_f CostToParkType_encode_der;
xer_type_decoder_f CostToParkType_decode_xer;
xer_type_encoder_f CostToParkType_encode_xer;
oer_type_decoder_f CostToParkType_decode_oer;
oer_type_encoder_f CostToParkType_encode_oer;
per_type_decoder_f CostToParkType_decode_uper;
per_type_encoder_f CostToParkType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CostToParkType_H_ */
#include <asn_internal.h>
