/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DataElementsModule"
 * 	found in "./DataElementsModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DSRCmsgIDType_H_
#define	_DSRCmsgIDType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRCmsgIDType {
	DSRCmsgIDType_mapData	= 18,
	DSRCmsgIDType_signalPhaseAndTimingMessage	= 19,
	DSRCmsgIDType_basicSafetyMessage	= 20,
	DSRCmsgIDType_commonSafetyRequest	= 21,
	DSRCmsgIDType_emergencyVehicleAlert	= 22,
	DSRCmsgIDType_intersectionCollision	= 23,
	DSRCmsgIDType_nmeaCorrections	= 24,
	DSRCmsgIDType_probeDataManagement	= 25,
	DSRCmsgIDType_probeVehicleData	= 26,
	DSRCmsgIDType_roadSideAlert	= 27,
	DSRCmsgIDType_rtcmCorrections	= 28,
	DSRCmsgIDType_signalRequestMessage	= 29,
	DSRCmsgIDType_signalStatusMessage	= 30,
	DSRCmsgIDType_travelerInformation	= 31,
	DSRCmsgIDType_personalSafetyMessage	= 32,
	DSRCmsgIDType_testMessage00	= 240,
	DSRCmsgIDType_testMessage01	= 241,
	DSRCmsgIDType_testMessage02	= 242,
	DSRCmsgIDType_testMessage03	= 243,
	DSRCmsgIDType_testMessage04	= 244,
	DSRCmsgIDType_testMessage05	= 245,
	DSRCmsgIDType_testMessage06	= 246,
	DSRCmsgIDType_testMessage07	= 247,
	DSRCmsgIDType_testMessage08	= 248,
	DSRCmsgIDType_testMessage09	= 249,
	DSRCmsgIDType_testMessage10	= 250,
	DSRCmsgIDType_testMessage11	= 251,
	DSRCmsgIDType_testMessage12	= 252,
	DSRCmsgIDType_testMessage13	= 253,
	DSRCmsgIDType_testMessage14	= 254,
	DSRCmsgIDType_testMessage15	= 255
} e_DSRCmsgIDType;

/* DSRCmsgIDType */
typedef long	 DSRCmsgIDType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSRCmsgIDType;
asn_struct_free_f DSRCmsgIDType_free;
asn_struct_print_f DSRCmsgIDType_print;
asn_constr_check_f DSRCmsgIDType_constraint;
ber_type_decoder_f DSRCmsgIDType_decode_ber;
der_type_encoder_f DSRCmsgIDType_encode_der;
xer_type_decoder_f DSRCmsgIDType_decode_xer;
xer_type_encoder_f DSRCmsgIDType_encode_xer;
oer_type_decoder_f DSRCmsgIDType_decode_oer;
oer_type_encoder_f DSRCmsgIDType_encode_oer;
per_type_decoder_f DSRCmsgIDType_decode_uper;
per_type_encoder_f DSRCmsgIDType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRCmsgIDType_H_ */
#include <asn_internal.h>
