/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DataElementsModule"
 * 	found in "./DataElementsModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_FreePlacesCountType_H_
#define	_FreePlacesCountType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FreePlacesCountType */
typedef long	 FreePlacesCountType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FreePlacesCountType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FreePlacesCountType;
asn_struct_free_f FreePlacesCountType_free;
asn_struct_print_f FreePlacesCountType_print;
asn_constr_check_f FreePlacesCountType_constraint;
ber_type_decoder_f FreePlacesCountType_decode_ber;
der_type_encoder_f FreePlacesCountType_encode_der;
xer_type_decoder_f FreePlacesCountType_decode_xer;
xer_type_encoder_f FreePlacesCountType_encode_xer;
oer_type_decoder_f FreePlacesCountType_decode_oer;
oer_type_encoder_f FreePlacesCountType_encode_oer;
per_type_decoder_f FreePlacesCountType_decode_uper;
per_type_encoder_f FreePlacesCountType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FreePlacesCountType_H_ */
#include <asn_internal.h>
