/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaneFrameModule"
 * 	found in "./LaneFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GenericLane_H_
#define	_GenericLane_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneID.h"
#include "DescriptiveName.h"
#include "ApproachID.h"
#include "LaneAttributes.h"
#include "AllowedManeuvers.h"
#include "NodeListXY.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConnectsToList;
struct OverlayLaneList;

/* GenericLane */
typedef struct GenericLane {
	LaneID_t	 laneID;
	DescriptiveName_t	*name	/* OPTIONAL */;
	ApproachID_t	*ingressApproach	/* OPTIONAL */;
	ApproachID_t	*egressApproach	/* OPTIONAL */;
	LaneAttributes_t	 laneAttributes;
	AllowedManeuvers_t	*maneuvers	/* OPTIONAL */;
	NodeListXY_t	 nodeList;
	struct ConnectsToList	*connectsTo	/* OPTIONAL */;
	struct OverlayLaneList	*overlays	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericLane;
extern asn_SEQUENCE_specifics_t asn_SPC_GenericLane_specs_1;
extern asn_TYPE_member_t asn_MBR_GenericLane_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConnectsToList.h"
#include "OverlayLaneList.h"

#endif	/* _GenericLane_H_ */
#include <asn_internal.h>
