/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MSGIntersectionCollisionAvoidanceModule"
 * 	found in "./MSGIntersectionCollisionAvoidanceModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_IntersectionCollision_H_
#define	_IntersectionCollision_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "TemporaryID.h"
#include "MinuteOfTheYear.h"
#include "IntersectionReferenceID.h"
#include "ApproachOrLane.h"
#include "VehicleEventFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BSMcoreData;
struct PathHistory;
struct PathPrediction;

/* IntersectionCollision */
typedef struct IntersectionCollision {
	MsgCount_t	 msgCnt;
	TemporaryID_t	 id;
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	struct BSMcoreData	*partOne	/* OPTIONAL */;
	struct PathHistory	*path	/* OPTIONAL */;
	struct PathPrediction	*pathPrediction	/* OPTIONAL */;
	IntersectionReferenceID_t	 intersectionID;
	ApproachOrLane_t	 laneNumber;
	VehicleEventFlags_t	 eventFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionCollision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionCollision;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BSMcoreData.h"
#include "PathHistory.h"
#include "PathPrediction.h"

#endif	/* _IntersectionCollision_H_ */
#include <asn_internal.h>
