/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MSGMapDataModule"
 * 	found in "./MSGMapDataModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_MapData_H_
#define	_MapData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MinuteOfTheYear.h"
#include "MsgCount.h"
#include "LayerType.h"
#include "LayerID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ParkingArea;
struct IntersectionGeometryList;
struct RoadSegmentList;
struct DataParameters;
struct RestrictionClassList;

/* MapData */
typedef struct MapData {
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	MsgCount_t	 msgIssueRevision;
	LayerType_t	*layerType	/* OPTIONAL */;
	LayerID_t	*layerID	/* OPTIONAL */;
	struct ParkingArea	*parkingAreas	/* OPTIONAL */;
	struct IntersectionGeometryList	*intersections	/* OPTIONAL */;
	struct RoadSegmentList	*roadSegments	/* OPTIONAL */;
	struct DataParameters	*dataParameters	/* OPTIONAL */;
	struct RestrictionClassList	*restrictionList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MapData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MapData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ParkingArea.h"
#include "IntersectionGeometryList.h"
#include "RoadSegmentList.h"
#include "DataParameters.h"
#include "RestrictionClassList.h"

#endif	/* _MapData_H_ */
#include <asn_internal.h>
