/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MSGMessageFrameModule"
 * 	found in "./MSGMessageFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_MessageFrame_H_
#define	_MessageFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "BasicSafetyMessage.h"
#include "MapData.h"
#include "SPAT.h"
#include "EmergencyVehicleAlert.h"
#include "IntersectionCollision.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum value_PR {
	value_PR_NOTHING,	/* No components present */
	value_PR_BasicSafetyMessage,
	value_PR_MapData,
	value_PR_SPAT,
	value_PR_EmergencyVehicleAlert,
	value_PR_IntersectionCollision
} value_PR;

/* MessageFrame */
typedef struct MessageFrame {
	DSRCmsgID_t	 messageId;
	struct value {
		value_PR present;
		union MessageFrame__value_u {
			BasicSafetyMessage_t	 BasicSafetyMessage;
			MapData_t	 MapData;
			SPAT_t	 SPAT;
			EmergencyVehicleAlert_t	 EmergencyVehicleAlert;
			IntersectionCollision_t	 IntersectionCollision;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageFrame_H_ */
#include <asn_internal.h>
