/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DataElementsModule"
 * 	found in "./DataElementsModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ParkingAreaID_H_
#define	_ParkingAreaID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ParkingAreaID */
typedef long	 ParkingAreaID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingAreaID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingAreaID;
asn_struct_free_f ParkingAreaID_free;
asn_struct_print_f ParkingAreaID_print;
asn_constr_check_f ParkingAreaID_constraint;
ber_type_decoder_f ParkingAreaID_decode_ber;
der_type_encoder_f ParkingAreaID_encode_der;
xer_type_decoder_f ParkingAreaID_decode_xer;
xer_type_encoder_f ParkingAreaID_encode_xer;
oer_type_decoder_f ParkingAreaID_decode_oer;
oer_type_encoder_f ParkingAreaID_encode_oer;
per_type_decoder_f ParkingAreaID_decode_uper;
per_type_encoder_f ParkingAreaID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingAreaID_H_ */
#include <asn_internal.h>
