/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DataElementsModule"
 * 	found in "./DataElementsModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ParkingAcessPointTypes_H_
#define	_ParkingAcessPointTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingAcessPointTypes {
	ParkingAcessPointTypes_entry	= 0,
	ParkingAcessPointTypes_exit	= 1
} e_ParkingAcessPointTypes;

/* ParkingAcessPointTypes */
typedef long	 ParkingAcessPointTypes_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingAcessPointTypes_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingAcessPointTypes;
extern const asn_INTEGER_specifics_t asn_SPC_ParkingAcessPointTypes_specs_1;
asn_struct_free_f ParkingAcessPointTypes_free;
asn_struct_print_f ParkingAcessPointTypes_print;
asn_constr_check_f ParkingAcessPointTypes_constraint;
ber_type_decoder_f ParkingAcessPointTypes_decode_ber;
der_type_encoder_f ParkingAcessPointTypes_encode_der;
xer_type_decoder_f ParkingAcessPointTypes_decode_xer;
xer_type_encoder_f ParkingAcessPointTypes_encode_xer;
oer_type_decoder_f ParkingAcessPointTypes_decode_oer;
oer_type_encoder_f ParkingAcessPointTypes_encode_oer;
per_type_decoder_f ParkingAcessPointTypes_decode_uper;
per_type_encoder_f ParkingAcessPointTypes_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingAcessPointTypes_H_ */
#include <asn_internal.h>
