/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ParkingAreaFrameModule"
 * 	found in "./ParkingAreaFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ParkingArea_H_
#define	_ParkingArea_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ParkingAreaID.h"
#include "ParkingAreaType.h"
#include "ParkingAcessPointTypes.h"
#include "FreePlacesCountType.h"
#include "CostToParkType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Position3D;
struct DTime;

/* ParkingArea */
typedef struct ParkingArea {
	ParkingAreaID_t	 id;
	ParkingAreaType_t	 type;
	struct accessPoints {
		A_SEQUENCE_OF(struct Position3D) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} accessPoints;
	ParkingAcessPointTypes_t	 accessPointType;
	FreePlacesCountType_t	 freePlacesCount;
	struct opens {
		A_SEQUENCE_OF(struct DTime) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} opens;
	struct closes {
		A_SEQUENCE_OF(struct DTime) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} closes;
	CostToParkType_t	 costToPark;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingArea_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingArea;
extern asn_SEQUENCE_specifics_t asn_SPC_ParkingArea_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingArea_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Position3D.h"
#include "DTime.h"

#endif	/* _ParkingArea_H_ */
#include <asn_internal.h>
