/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MSGRoadSideAlertModule"
 * 	found in "./MSGRoadSideAlertModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RoadSideAlert_H_
#define	_RoadSideAlert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "MinuteOfTheYear.h"
#include "ITIScodes.h"
#include "Priority.h"
#include "HeadingSlice.h"
#include "Extent.h"
#include "FurtherInfoID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FullPositionVector;

/* RoadSideAlert */
typedef struct RoadSideAlert {
	MsgCount_t	 msgCnt;
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	ITIScodes_t	 typeEvent;
	Priority_t	*priority	/* OPTIONAL */;
	HeadingSlice_t	*heading	/* OPTIONAL */;
	Extent_t	*extent	/* OPTIONAL */;
	struct FullPositionVector	*position	/* OPTIONAL */;
	FurtherInfoID_t	*furtherInfoID	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSideAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSideAlert;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadSideAlert_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSideAlert_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FullPositionVector.h"

#endif	/* _RoadSideAlert_H_ */
#include <asn_internal.h>
