/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MSGSignalStatusMessageFrameModule"
 * 	found in "./MSGSignalStatusMessageFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SignalStatusMessage_H_
#define	_SignalStatusMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "MsgCount.h"
#include "SignalStatusList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalStatusMessage */
typedef struct SignalStatusMessage {
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	DSecond_t	 second;
	MsgCount_t	*sequenceNumber	/* OPTIONAL */;
	SignalStatusList_t	 status;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalStatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalStatusMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalStatusMessage_H_ */
#include <asn_internal.h>
