/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SignalRequestPackageFrameModule"
 * 	found in "./SignalRequestPackageFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SignalRequestPackage_H_
#define	_SignalRequestPackage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignalRequest.h"
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalRequestPackage */
typedef struct SignalRequestPackage {
	SignalRequest_t	 request;
	MinuteOfTheYear_t	*minute	/* OPTIONAL */;
	DSecond_t	*second	/* OPTIONAL */;
	DSecond_t	*duration	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestPackage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestPackage;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalRequestPackage_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalRequestPackage_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SignalRequestPackage_H_ */
#include <asn_internal.h>
