/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MSGSignalRequestMessageFrameModule"
 * 	found in "./MSGSignalRequestMessageFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SignalRequestMessage_H_
#define	_SignalRequestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "MsgCount.h"
#include "RequestorDescription.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignalRequestList;

/* SignalRequestMessage */
typedef struct SignalRequestMessage {
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	DSecond_t	 second;
	MsgCount_t	*sequenceNumber	/* OPTIONAL */;
	struct SignalRequestList	*requests	/* OPTIONAL */;
	RequestorDescription_t	 requestor;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignalRequestList.h"

#endif	/* _SignalRequestMessage_H_ */
#include <asn_internal.h>
