/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IntersectionFrameModule"
 * 	found in "./IntersectionFrameModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SignalControlZone_H_
#define	_SignalControlZone_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalControlZone */
typedef struct SignalControlZone {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalControlZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalControlZone;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalControlZone_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalControlZone_H_ */
#include <asn_internal.h>
